class Sport:
    soccer = 'soccer'
    hockey = 'hockey'
    basketball = 'basketball'
    tennis = 'tennis'
    table_tennis = 'table_tennis'
    volleyball = 'volleyball'
    beach_volley = 'beach_volley'
    esports = 'esports'
    badminton = 'badminton'